Mention life-cycle API in Request assertions recipe
mswjs/mswjs.io pull request #147
Opened 2021-06-08 19:34 UTC by Izhaki

resolves https://github.com/mswjs/msw/issues/719

2021-06-09 11:59 UTC, kettanaito commented on docs/recipes/request-assertions.mdx
> +For such cases, Mock Service Worker allows tracking of network requests through the [Life-cycle events API](https://mswjs.io/docs/extensions/life-cycle-events#tracking-a-request).
Could you please use a relative path to the page in the docs?

```suggestion
For such cases, Mock Service Worker allows tracking of network requests through the [Life-cycle events API](/docs/extensions/life-cycle-events#tracking-a-request).
```

Thanks!

2021-06-09 11:59 UTC, kettanaito requested changes
Hey, @Izhaki. Thank you for adding this!
Please, could you fix the link to the page in the docs?

2021-06-09 13:41 UTC, kettanaito requested changes
Do you think it'd make more sense if we moved this section to the very bottom of the page?
I think that the order in which we suggest the approaches matters, and "special cases" is the last resort if any other suggestion is not applicable. We still want the readers to go through those suggestions to assess their relevance.

2021-06-09 15:15 UTC, Izhaki commented
@kettanaito For me, I was looking for a way to assert on requests, which is how I ended up looking at the `Request assertions` section.

The content under `Request assertions` makes it pretty clear you shouldn't assert on requests.

The following sections - `Include failure scenarios` and `Treat unhandled requests` discuss other best practices. So at that point the reader might conclude asserting on requests is not possible, and it will take scrolling to reveal otherwise.

So for me, `Special cases` is tightly linked to the `Request assertions` heading and the text under it.

There is possibly a bigger structural issues on the page - do `Include failure scenarios` and `Treat unhandled requests` truly belong to `Request assertions`? After all, there nothing in them that relates to assertions... and that's why the confusion.

It would possibly make more sense if the whole page would be called `Testing Strategies` and the headings would be as follows:

```
# Testing Strategies
## Request assertions
### Special cases
## Include failure scenarios
## Treat unhandled requests
```

Let me know what you think.

2021-06-14 19:23 UTC, Izhaki commented
I guess I'm waiting for feedback?

2021-07-31 11:40 UTC, kettanaito approved these changes
This is a good addition and can be merged as-is. Let's iterate on it if need be. Thank you, @Izhaki!

2021-07-31 11:40 UTC, merged