Update jest-missing-globals.mdx
mswjs/mswjs.io pull request #353
Opened 2024-01-22 12:00 UTC by barisbll

ReadableStream also have to be added in order this solution to work

In this discussion it is written clearly https://github.com/mswjs/msw/discussions/1934#discussioncomment-7874204

2024-02-13 13:40 UTC, MichaelDeBoey requested changes

2024-02-13 13:40 UTC, MichaelDeBoey commented on src/content/docs/shared/jest-missing-globals.mdx
> +const { TextDecoder, TextEncoder, ReadableStream } = require("node:util")
I think we should keep quotes as they are

```suggestion
const { TextDecoder, TextEncoder, ReadableStream } = require('node:util')
```

2024-02-13 13:40 UTC, MichaelDeBoey commented on src/content/docs/shared/jest-missing-globals.mdx
> +const { fetch, Headers, FormData, Request, Response } = require("undici")
```suggestion
const { Blob, File } = require('node:buffer')
const { fetch, Headers, FormData, Request, Response } = require('undici')
```

2024-02-13 14:14 UTC, kettanaito commented on src/content/docs/shared/jest-missing-globals.mdx
> +const { TextDecoder, TextEncoder, ReadableStream } = require("node:util")
This is incorrect though. Must be imported from `node:stream/web`. That's the correct implementation of web's `ReadableStream`.

2024-02-13 14:30 UTC, kettanaito commented
There's also a fundamental problem of polyfilling `ReadableStream`. If you polyfill it, it will start requiring built-in Node.js modules, likes `structuredClone()`, which will be polyfilled in Jest, and polyfilled incorrectly, breaking your tests pretty much forever. 

See more details here: https://github.com/mswjs/msw/issues/1916#issuecomment-1908544946.

**This is why recommending polyfilling `ReadableStream` to everyone by default is dangerous**.

2024-09-26 10:31 UTC, kettanaito commented
Fixed by #419.

2024-09-26 10:31 UTC, closed without merging